version: '3.9'

services:

  ezserver-app:
    container_name: ezserver_app
    image: meetunix/ezserver:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:18080:8080"
    environment:
      CONF_FILE: "server-h2-persistent.properties"
      EZSERVER_LOG_LEVEL: info
    volumes:
        -   "ezserver_h2_logs:/log"
        -   "ezserver_h2_db:/ezdb"

volumes:
  ezserver_h2_db:
  ezserver_h2_logs:
